management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  my-app:
    any-value: someValue
    group-id: "@project.groupId@"
    artifact-id: "@project.artifactId@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
  made-by: developerY